#!/bin/bash

bateria(){
bat=$($HOME/.config/dwm/scripts/battery)

}

relogio(){
clock=$($HOME/.config/dwm/scripts/clock)
}

processador(){
cpu=$($HOME/.config/dwm/scripts/cpu)
}

disco(){
home=$($HOME/.config/dwm/scripts/disk /home)
root=$($HOME/.config/dwm/scripts/disk /)
}

internet(){
inter=$($HOME/.config/dwm/scripts/internet)
}
volume(){
vol=$($HOME/.config/dwm/scripts/volume)
}
musica(){
music=$($HOME/.config/dwm/scripts/music)
}

while [ 1 ]
do bateria
relogio
processador
disco
internet
volume
musica

xsetroot -name "${cpu} | ${inter} | ${home} | ${root} | ${musica} ${vol} | ${bat} | ${clock}"
sleep 1
done
