#!/bin/bash
originaloc=$HOME/.config/dwm/scripts/

bateria(){
bat=$(${originaloc}battery)
}

relogio(){
clock=$(${originaloc}clock)
}

processador(){
cpu=$(${originaloc}cpu)
}

disco(){
home=$(${originaloc}disk /home)
root=$(${originaloc}disk /)
}

internet(){
inter=$(${originaloc}internet)
}

volume(){
vol=$(${originaloc}volume)
}

musica(){
music=$(${originaloc}musica)
}

while [ 1 ]
do bateria
relogio
processador
disco
internet
volume
musica

xsetroot -name "${cpu} | ${inter} | ${home} | ${root} | ${vol} | ${bat} | ${clock}"
sleep 1m
done
